[package]

name = "debugln"
version = "0.1.0"
authors = ["Zach Pomerantz <zach@terminal.com>"]
repository = "https://github.com/zzmp/rust-debug.git"
description = "println!() in debug, noop in release."
readme = "README.md"
license = "MIT"

[lib]

name = "debugln"
path = "src/lib.rs"
