[package]

name = "debugln"
version = "0.0.1"
authors = ["Zach Pomerantz <zach@terminal.com>"]
repository = "https://github.com/zzmp/rust-debug.git"
description = "println!() in debug, noop in release."
readme = "README.md"
license = "MIT"

[lib]

name = "debug"
path = "src/lib.rs"
plugin = true

